### ISSUE TITLE
posix semantics on windows

### ISSUE THREAD

**Issue by rbtcollins** [rbtcollins/fs_at#63]
We should use posix semantics to delete on windows. 

Rust [platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1-with-host-tools) claims windows 7 and up.

I can't find any reference to the necessary structure to request this the way the [stdlib does](
https://github.com/rust-lang/rust/blob/df7fd9995f10627f25ccb325f693a11b3395a73c/library/std/src/sys/windows/fs.rs#L612) in the MS docs. The [closest I've come](https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ne-minwinbase-file_info_by_handle_class) just notes its existence, not when APIs started accepting it, nor what will happen on older Windows versions if the structure class, or bits in the flag that were defined more recently are passed in.

@ChrisDenton sorry for tagging you out of the blue but I'm hoping you can give a little guidance / point to docs about the thing to do here. 

My inclination was to first version-check the runtime OS for windows 10, and then and only then attempt the new information class, falling back on error to the older class, but the Rust stdlib seems to unconditionally use the new information class, so if thats safe it seems more straightforward...

**Comment by ChrisDenton** [comment]
I don't mind being tagged at all.

std currently does fallback to the standard `DISPOSITION_INFO` (instead of `DISPOSITION_INFO_EX`) if [certain errors are encountered](https://github.com/rust-lang/rust/blob/df7fd9995f10627f25ccb325f693a11b3395a73c/library/std/src/sys/windows/fs.rs#L1091-L1096). Specifically: `ERROR_NOT_SUPPORTED`, `ERROR_INVALID_FUNCTION` and `ERROR_INVALID_PARAMETER`.

Version support doesn't appear to be documented online but the public SDK headers do have some version info:

```c
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN10_RS1)
#define FILE_DISPOSITION_FLAG_DO_NOT_DELETE              0x00000000
#define FILE_DISPOSITION_FLAG_DELETE                     0x00000001
#define FILE_DISPOSITION_FLAG_POSIX_SEMANTICS            0x00000002
#define FILE_DISPOSITION_FLAG_FORCE_IMAGE_SECTION_CHECK  0x00000004
#define FILE_DISPOSITION_FLAG_ON_CLOSE                   0x00000008
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN10_RS5)
#define FILE_DISPOSITION_FLAG_IGNORE_READONLY_ATTRIBUTE  0x00000010
#endif
```

`_WIN32_WINNT_WIN10_RS1` == Windows 10 version 1607
`_WIN32_WINNT_WIN10_RS5` == Windows 10 version 1809

Note that the std currently implements an "all or nothing" strategy. Either all the flags work or it falls back to the old-style delete. There is certainly room for supporting more in-between versions of Windows here.

I would caution against relying on version detection though. POSIX delete may not work on all filesystems even on the latest versions of Windows.

**Comment by rbtcollins** [comment]
Thank you! I think my main question was 'is it safe to just call these newer APIs' ? Since the interface doesn't seem to be versioned externally.
